### ISSUE TITLE
Export dballe verso R

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/dballe#120]
Qualcuno sta facendo export da DB-ALl.e verso R, vuoi via python vuoi via provami?

**Comment by brancomat** [comment]
Per quel che mi riguarda no, ho parlato con un paio di power user di R nostrani (Maria Stefania e Roberta) anche per loro è no.

Come si diceva con @edigiacomo al momento sospenderei i test legati a rpy per permettere la compilazione dell'ultimo dballe su tutti i sistemi per poi dismettere quella parte se la issue.

Nel caso si rendesse necessario ripristinare la cosa, appunto qui l'analisi fatta da @edigiacomo sugli step necessari:

- FC20: in dismissione, rimane tutto fermo a com'è.
- FC24: nessun problema, esistono `python2-rpy` e `python3-rpy`.
- FC28: non c'è il pacchetto `python2-rpy`, quindi è da fare (sempre che la versione di rpy su FC28 non sia passata a supportare solo Python3) oppure disattiviamo `python2-dballe` per questa versione.
- CentOS: facciamo il pacchetto `python2-rpy` e `python3-rpy`.

**Comment by pat1** [comment]
R è un software principalmente per statistica e che io sappia l'esportazione a R non è itilizzata per cose "operative"; è invece stata utilizzata e potrebbe essere utilizzata in fase di sviluppo e ricerca e unica alternativa è il csv che io come sapete vorrei eliminare dal mondo.
Perdere l'esportazione definitivamente non mi soddisfa; è accettabile perderla temporaneamente e se questa poi è recuperabile con la migrazione di tutto il python a python3 proporrei questa strada (faticosa anche per me) che è comunque inevitabile.

**Comment by amontani** [comment]
Maybe, there is an issue with export to Rdata format , which is becoming useful for  verification of ensemble forecast data:

export stringa=`echo --dsn=postgresql://vpavan:80qwfwq@localhost/soglie`
dbaexport   $stringa  --outfile zzz.gnur 'gnur'

Traceback (most recent call last):
  File "/usr/bin/dbaexport", line 125, in <module>
    dballe.rconvert.volnd_save_to_r(res, args.outfile)
  File "/usr/lib/python2.7/site-packages/dballe/rconvert.py", line 85, in volnd_save_to_r
    robjects.r.assign(k, volnd_data_to_r(d))
  File "/usr/lib/python2.7/site-packages/dballe/rconvert.py", line 74, in volnd_data_to_r
    return ma_to_r(data.vals, dimnames=dn)
  File "/usr/lib/python2.7/site-packages/dballe/rconvert.py", line 54, in ma_to_r
    vec = rinterface.FloatSexpVector(ma_to_rlist(farray))
  File "/usr/lib/python2.7/site-packages/dballe/rconvert.py", line 33, in ma_to_rlist
    ma_data = arr.data.ravel("F")
MemoryError

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
