### ISSUE TITLE
build documentation fail

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#169]
./rebuild-gh-pages

end with:

```
Making all in .
make[2]: ingresso nella directory "/tmp/ppatruno/tmpp5om1bxd/build"
( cd src && ./`basename src/dbatbl` help manpage ) > dbatbl.1
( cd src && ./`basename src/dbamsg` help manpage ) | ( cd . && ./doc/add_templates_to_manpage ) > dbamsg.1
( cd src && ./`basename src/dbadb` help manpage ) | ( cd . && ./doc/add_templates_to_manpage ) > dbadb.1
make[2]: uscita dalla directory "/tmp/ppatruno/tmpp5om1bxd/build"
make[1]: uscita dalla directory "/tmp/ppatruno/tmpp5om1bxd/build"
Clone in 'pages' in corso...
fatto.
Si è passati a un nuovo branch 'gh-pages'
Traceback (most recent call last):
  File "./rebuild-gh-pages", line 101, in <module>
    main()
  File "./rebuild-gh-pages", line 97, in main
    builder.publish(os.path.join(builder.builddir, "doc", "html"))
  File "./rebuild-gh-pages", line 55, in publish
    for fn in os.listdir(built_pages):
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ppatruno/tmpp5om1bxd/build/doc/html'
```

**Comment by pat1** [comment]
package libwreport-doc was missed
