### ISSUE TITLE
pyhon api: in documentation example error

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#178]
The first example do not work:
https://arpa-simc.github.io/dballe/python/dballe_db.html

```
python test.py 
  File "test.py", line 3
    query = {latmin=44.0, latmax=45.0, lonmin=11.0, lonmax=12.0}
                   ^
SyntaxError: invalid syntax

```
solving syntax error I go into #177
removin lon extreme:

```
python test2.py 
test2.py:9: DeprecationWarning: calling query_data without a transaction is deprecated
  for row in db.query_data(query):
Traceback (most recent call last):
  File "test2.py", line 10, in <module>
    print(row["lat"], row["lon"], row["var"], row.var().format("undefined"))
AttributeError: 'dballe.CursorDataDB' object has no attribute 'var'

```

**Comment by spanezz** [comment]
I fixed the docstring: now it's db["variable"] to get the variable associated with the current row, so that all access happens via indexing.
