### ISSUE TITLE
segfault from python API

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#190]
I do not know how to debug better in this case ...

```
gdb python ./rmapweb 
GNU gdb (GDB) Fedora 8.3.50.20190824-24.fc31
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...
Reading symbols from .gnu_debugdata for /usr/bin/python3.7...
(No debugging symbols found in .gnu_debugdata for /usr/bin/python3.7)
"/home/pat1/git/rmap/python/./rmapweb" is not a core dump: file format not recognized
Missing separate debuginfos, use: dnf debuginfo-install python-unversioned-command-3.7.5-1.fc31.noarch
(gdb) run rmapweb
Starting program: /usr/bin/python rmapweb
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Rmapweb version 9.0
Daemon started with pid 4578
Daemon stdout output
Daemon stderr output
/home/pat1/git/rmap/python/cache/
import error:  django_extensions
disable     :  ('django_extensions',)
[New Thread 0x7fffe5ecc700 (LWP 4582)]
[New Thread 0x7fffe56cb700 (LWP 4583)]
[New Thread 0x7fffe2eca700 (LWP 4584)]
[New Thread 0x7fffde6c9700 (LWP 4585)]
[New Thread 0x7fffdbec8700 (LWP 4586)]
[New Thread 0x7fffd96c7700 (LWP 4587)]
[New Thread 0x7fffd6ec6700 (LWP 4588)]
[Thread 0x7fffd6ec6700 (LWP 4588) exited]
[Thread 0x7fffd96c7700 (LWP 4587) exited]
[Thread 0x7fffdbec8700 (LWP 4586) exited]
[Thread 0x7fffde6c9700 (LWP 4585) exited]
[Thread 0x7fffe2eca700 (LWP 4584) exited]
[Thread 0x7fffe56cb700 (LWP 4583) exited]
[Thread 0x7fffe5ecc700 (LWP 4582) exited]
[Detaching after fork from child process 4589]
warning: Loadable section ".note.gnu.property" outside of ELF segments
[Detaching after fork from child process 4590]
Performing system checks...

[Detaching after fork from child process 4591]
System check identified no issues (0 silenced).
November 14, 2019 - 13:15:58
Django version 2.2.5, using settings 'rmap.settings'
Starting development server at http://127.0.0.1:8888/
Quit the server with CONTROL-C.
[New Thread 0x7fffd6ec6700 (LWP 4605)]

Thread 9 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd6ec6700 (LWP 4605)]
0x00007ffff7f31ce7 in __strlen_avx2 () from /lib64/libc.so.6
(gdb) where
#0  0x00007ffff7f31ce7 in __strlen_avx2 () from /lib64/libc.so.6
#1  0x00007ffff7b91679 in PyUnicode_FromString ()
   from /lib64/libpython3.7m.so.1.0
#2  0x00007fffd38ef4e9 in dballe::python::Enqpy::set_ident(dballe::Ident const&) () from /usr/lib64/python3.7/site-packages/_dballe.so
#3  0x00007fffd3908609 in ?? ()
   from /usr/lib64/python3.7/site-packages/_dballe.so
#4  0x00007ffff7b95cb8 in PyObject_GetItem () from /lib64/libpython3.7m.so.1.0
#5  0x00007ffff7bfcdc7 in _PyEval_EvalFrameDefault ()
   from /lib64/libpython3.7m.so.1.0
#6  0x00007ffff7bb526a in _PyFunction_FastCallDict ()
   from /lib64/libpython3.7m.so.1.0
#7  0x00007ffff7b88e26 in _PyObject_Call_Prepend ()
   from /lib64/libpython3.7m.so.1.0
#8  0x00007ffff7b84b45 in _PyObject_FastCallDict ()
   from /lib64/libpython3.7m.so.1.0
#9  0x00007ffff7b9235f in object_vacall () from /lib64/libpython3.7m.so.1.0
#10 0x00007ffff7b92599 in PyObject_CallFunctionObjArgs ()
   from /lib64/libpython3.7m.so.1.0
#11 0x00007ffff7b93d6d in list_sort_impl () from /lib64/libpython3.7m.so.1.0
#12 0x00007ffff7bcdde6 in list_sort () from /lib64/libpython3.7m.so.1.0
#13 0x00007ffff7b93528 in _PyMethodDef_RawFastCallKeywords ()
   from /lib64/libpython3.7m.so.1.0
--Type <RET> for more, q to quit, c to continue without paging--
#14 0x00007ffff7b937c3 in _PyCFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#15 0x00007ffff7bc5561 in builtin_sorted () from /lib64/libpython3.7m.so.1.0
#16 0x00007ffff7b93528 in _PyMethodDef_RawFastCallKeywords () from /lib64/libpython3.7m.so.1.0
#17 0x00007ffff7b937c3 in _PyCFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#18 0x00007ffff7bc6503 in call_function () from /lib64/libpython3.7m.so.1.0
#19 0x00007ffff7bfd838 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#20 0x00007ffff7bc56d5 in gen_iternext () from /lib64/libpython3.7m.so.1.0
#21 0x00007ffff7bfcc6c in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#22 0x00007ffff7bc56d5 in gen_iternext () from /lib64/libpython3.7m.so.1.0
#23 0x00007ffff7bfcc6c in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#24 0x00007ffff7bb3d90 in _PyEval_EvalCodeWithName () from /lib64/libpython3.7m.so.1.0
#25 0x00007ffff7bb4da2 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#26 0x00007ffff7bc63ef in call_function () from /lib64/libpython3.7m.so.1.0
#27 0x00007ffff7bfca68 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#28 0x00007ffff7bb4c02 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#29 0x00007ffff7bc63ef in call_function () from /lib64/libpython3.7m.so.1.0
#30 0x00007ffff7bfcb0c in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#31 0x00007ffff7bb4c02 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#32 0x00007ffff7bc63ef in call_function () from /lib64/libpython3.7m.so.1.0
#33 0x00007ffff7bfcb0c in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#34 0x00007ffff7bb4c02 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#35 0x00007ffff7bc63ef in call_function () from /lib64/libpython3.7m.so.1.0
#36 0x00007ffff7bfcb0c in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#37 0x00007ffff7bb526a in _PyFunction_FastCallDict () from /lib64/libpython3.7m.so.1.0
#38 0x00007ffff7c19982 in call_unbound_noarg () from /lib64/libpython3.7m.so.1.0
#39 0x00007ffff7c41c48 in slot_tp_iter () from /lib64/libpython3.7m.so.1.0
#40 0x00007ffff7b85499 in PyObject_GetIter () from /lib64/libpython3.7m.so.1.0
#41 0x00007ffff7c34fc5 in islice_new () from /lib64/libpython3.7m.so.1.0
#42 0x00007ffff7bc4ec5 in _PyObject_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#43 0x00007ffff7bc6579 in call_function () from /lib64/libpython3.7m.so.1.0
#44 0x00007ffff7c014c2 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#45 0x00007ffff7bb3d90 in _PyEval_EvalCodeWithName () from /lib64/libpython3.7m.so.1.0
#46 0x00007ffff7bb543e in _PyFunction_FastCallDict () from /lib64/libpython3.7m.so.1.0
#47 0x00007ffff7bfe214 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#48 0x00007ffff7bb4c02 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#49 0x00007ffff7bc63ef in call_function () from /lib64/libpython3.7m.so.1.0
#50 0x00007ffff7bfca68 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#51 0x00007ffff7bb3d90 in _PyEval_EvalCodeWithName () from /lib64/libpython3.7m.so.1.0
#52 0x00007ffff7bb4da2 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#53 0x00007ffff7bc63ef in call_function () from /lib64/libpython3.7m.so.1.0
#54 0x00007ffff7c014c2 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
--Type <RET> for more, q to quit, c to continue without paging--
#55 0x00007ffff7bb526a in _PyFunction_FastCallDict () from /lib64/libpython3.7m.so.1.0
#56 0x00007ffff7b88e26 in _PyObject_Call_Prepend () from /lib64/libpython3.7m.so.1.0
#57 0x00007ffff7c48939 in slot_tp_call () from /lib64/libpython3.7m.so.1.0
#58 0x00007ffff7bc52cc in _PyObject_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#59 0x00007ffff7bc6579 in call_function () from /lib64/libpython3.7m.so.1.0
#60 0x00007ffff7bfca68 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#61 0x00007ffff7bb3d90 in _PyEval_EvalCodeWithName () from /lib64/libpython3.7m.so.1.0
#62 0x00007ffff7bb4da2 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#63 0x00007ffff7bc63ef in call_function () from /lib64/libpython3.7m.so.1.0
#64 0x00007ffff7c014c2 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#65 0x00007ffff7bb526a in _PyFunction_FastCallDict () from /lib64/libpython3.7m.so.1.0
#66 0x00007ffff7b88e26 in _PyObject_Call_Prepend () from /lib64/libpython3.7m.so.1.0
#67 0x00007ffff7c48939 in slot_tp_call () from /lib64/libpython3.7m.so.1.0
#68 0x00007ffff7bc52cc in _PyObject_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#69 0x00007ffff7bc6579 in call_function () from /lib64/libpython3.7m.so.1.0
#70 0x00007ffff7bfca68 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#71 0x00007ffff7bb3d90 in _PyEval_EvalCodeWithName () from /lib64/libpython3.7m.so.1.0
#72 0x00007ffff7bb4da2 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#73 0x00007ffff7bc63ef in call_function () from /lib64/libpython3.7m.so.1.0
#74 0x00007ffff7c014c2 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#75 0x00007ffff7bb526a in _PyFunction_FastCallDict () from /lib64/libpython3.7m.so.1.0
#76 0x00007ffff7b88e26 in _PyObject_Call_Prepend () from /lib64/libpython3.7m.so.1.0
#77 0x00007ffff7c48939 in slot_tp_call () from /lib64/libpython3.7m.so.1.0
#78 0x00007ffff7bc52cc in _PyObject_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#79 0x00007ffff7bc6579 in call_function () from /lib64/libpython3.7m.so.1.0
#80 0x00007ffff7bfca68 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#81 0x00007ffff7bb3d90 in _PyEval_EvalCodeWithName () from /lib64/libpython3.7m.so.1.0
#82 0x00007ffff7bb4da2 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#83 0x00007ffff7bc63ef in call_function () from /lib64/libpython3.7m.so.1.0
#84 0x00007ffff7c014c2 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#85 0x00007ffff7bb526a in _PyFunction_FastCallDict () from /lib64/libpython3.7m.so.1.0
#86 0x00007ffff7b88e26 in _PyObject_Call_Prepend () from /lib64/libpython3.7m.so.1.0
#87 0x00007ffff7c48939 in slot_tp_call () from /lib64/libpython3.7m.so.1.0
#88 0x00007ffff7bc52cc in _PyObject_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#89 0x00007ffff7bc6579 in call_function () from /lib64/libpython3.7m.so.1.0
#90 0x00007ffff7bfca68 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#91 0x00007ffff7bb3d90 in _PyEval_EvalCodeWithName () from /lib64/libpython3.7m.so.1.0
#92 0x00007ffff7bb4da2 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#93 0x00007ffff7bc63ef in call_function () from /lib64/libpython3.7m.so.1.0
#94 0x00007ffff7c014c2 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#95 0x00007ffff7bb526a in _PyFunction_FastCallDict () from /lib64/libpython3.7m.so.1.0
--Type <RET> for more, q to quit, c to continue without paging--
#96 0x00007ffff7b88e26 in _PyObject_Call_Prepend () from /lib64/libpython3.7m.so.1.0
#97 0x00007ffff7c48939 in slot_tp_call () from /lib64/libpython3.7m.so.1.0
#98 0x00007ffff7bc52cc in _PyObject_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#99 0x00007ffff7bc6579 in call_function () from /lib64/libpython3.7m.so.1.0
#100 0x00007ffff7bfca68 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#101 0x00007ffff7bb3d90 in _PyEval_EvalCodeWithName () from /lib64/libpython3.7m.so.1.0
#102 0x00007ffff7bb4da2 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#103 0x00007ffff7bc63ef in call_function () from /lib64/libpython3.7m.so.1.0
#104 0x00007ffff7c014c2 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#105 0x00007ffff7bb526a in _PyFunction_FastCallDict () from /lib64/libpython3.7m.so.1.0
#106 0x00007ffff7b88e26 in _PyObject_Call_Prepend () from /lib64/libpython3.7m.so.1.0
#107 0x00007ffff7c48939 in slot_tp_call () from /lib64/libpython3.7m.so.1.0
#108 0x00007ffff7bc52cc in _PyObject_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#109 0x00007ffff7bc6579 in call_function () from /lib64/libpython3.7m.so.1.0
#110 0x00007ffff7bfca68 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#111 0x00007ffff7bb3d90 in _PyEval_EvalCodeWithName () from /lib64/libpython3.7m.so.1.0
#112 0x00007ffff7bb4da2 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#113 0x00007ffff7bc63ef in call_function () from /lib64/libpython3.7m.so.1.0
#114 0x00007ffff7c014c2 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#115 0x00007ffff7bb526a in _PyFunction_FastCallDict () from /lib64/libpython3.7m.so.1.0
#116 0x00007ffff7b88e26 in _PyObject_Call_Prepend () from /lib64/libpython3.7m.so.1.0
#117 0x00007ffff7c48939 in slot_tp_call () from /lib64/libpython3.7m.so.1.0
#118 0x00007ffff7bc52cc in _PyObject_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#119 0x00007ffff7bc6579 in call_function () from /lib64/libpython3.7m.so.1.0
#120 0x00007ffff7bfca68 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#121 0x00007ffff7bb3d90 in _PyEval_EvalCodeWithName () from /lib64/libpython3.7m.so.1.0
#122 0x00007ffff7bb4da2 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#123 0x00007ffff7bc63ef in call_function () from /lib64/libpython3.7m.so.1.0
#124 0x00007ffff7c014c2 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#125 0x00007ffff7bb526a in _PyFunction_FastCallDict () from /lib64/libpython3.7m.so.1.0
#126 0x00007ffff7b88e26 in _PyObject_Call_Prepend () from /lib64/libpython3.7m.so.1.0
#127 0x00007ffff7c48939 in slot_tp_call () from /lib64/libpython3.7m.so.1.0
#128 0x00007ffff7bc52cc in _PyObject_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#129 0x00007ffff7bc6579 in call_function () from /lib64/libpython3.7m.so.1.0
#130 0x00007ffff7bfca68 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#131 0x00007ffff7bb3d90 in _PyEval_EvalCodeWithName () from /lib64/libpython3.7m.so.1.0
#132 0x00007ffff7bb4da2 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#133 0x00007ffff7bc63ef in call_function () from /lib64/libpython3.7m.so.1.0
#134 0x00007ffff7c014c2 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#135 0x00007ffff7bb526a in _PyFunction_FastCallDict () from /lib64/libpython3.7m.so.1.0
#136 0x00007ffff7b88e26 in _PyObject_Call_Prepend () from /lib64/libpython3.7m.so.1.0
--Type <RET> for more, q to quit, c to continue without paging--
#137 0x00007ffff7c48939 in slot_tp_call () from /lib64/libpython3.7m.so.1.0
#138 0x00007ffff7bc52cc in _PyObject_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#139 0x00007ffff7bc6579 in call_function () from /lib64/libpython3.7m.so.1.0
#140 0x00007ffff7bfca68 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#141 0x00007ffff7bb3d90 in _PyEval_EvalCodeWithName () from /lib64/libpython3.7m.so.1.0
#142 0x00007ffff7bb4da2 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#143 0x00007ffff7bc63ef in call_function () from /lib64/libpython3.7m.so.1.0
#144 0x00007ffff7c014c2 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#145 0x00007ffff7bb526a in _PyFunction_FastCallDict () from /lib64/libpython3.7m.so.1.0
#146 0x00007ffff7b88e26 in _PyObject_Call_Prepend () from /lib64/libpython3.7m.so.1.0
#147 0x00007ffff7c48939 in slot_tp_call () from /lib64/libpython3.7m.so.1.0
#148 0x00007ffff7bc52cc in _PyObject_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#149 0x00007ffff7bc6579 in call_function () from /lib64/libpython3.7m.so.1.0
#150 0x00007ffff7bfca68 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#151 0x00007ffff7bb3d90 in _PyEval_EvalCodeWithName () from /lib64/libpython3.7m.so.1.0
#152 0x00007ffff7bb4da2 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#153 0x00007ffff7bc63ef in call_function () from /lib64/libpython3.7m.so.1.0
#154 0x00007ffff7c014c2 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#155 0x00007ffff7bb526a in _PyFunction_FastCallDict () from /lib64/libpython3.7m.so.1.0
#156 0x00007ffff7b88e26 in _PyObject_Call_Prepend () from /lib64/libpython3.7m.so.1.0
#157 0x00007ffff7c48939 in slot_tp_call () from /lib64/libpython3.7m.so.1.0
#158 0x00007ffff7bc52cc in _PyObject_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#159 0x00007ffff7bc6579 in call_function () from /lib64/libpython3.7m.so.1.0
#160 0x00007ffff7bfca68 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#161 0x00007ffff7bb3d90 in _PyEval_EvalCodeWithName () from /lib64/libpython3.7m.so.1.0
#162 0x00007ffff7bb4da2 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#163 0x00007ffff7bc63ef in call_function () from /lib64/libpython3.7m.so.1.0
#164 0x00007ffff7c014c2 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#165 0x00007ffff7bb526a in _PyFunction_FastCallDict () from /lib64/libpython3.7m.so.1.0
#166 0x00007ffff7b88e26 in _PyObject_Call_Prepend () from /lib64/libpython3.7m.so.1.0
#167 0x00007ffff7c48939 in slot_tp_call () from /lib64/libpython3.7m.so.1.0
#168 0x00007ffff7bc52cc in _PyObject_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#169 0x00007ffff7bc6579 in call_function () from /lib64/libpython3.7m.so.1.0
#170 0x00007ffff7bfca68 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#171 0x00007ffff7bb3d90 in _PyEval_EvalCodeWithName () from /lib64/libpython3.7m.so.1.0
#172 0x00007ffff7bb4da2 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#173 0x00007ffff7bc63ef in call_function () from /lib64/libpython3.7m.so.1.0
#174 0x00007ffff7c014c2 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#175 0x00007ffff7bb526a in _PyFunction_FastCallDict () from /lib64/libpython3.7m.so.1.0
#176 0x00007ffff7b88e26 in _PyObject_Call_Prepend () from /lib64/libpython3.7m.so.1.0
#177 0x00007ffff7c48939 in slot_tp_call () from /lib64/libpython3.7m.so.1.0
--Type <RET> for more, q to quit, c to continue without paging--
#178 0x00007ffff7bc52cc in _PyObject_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#179 0x00007ffff7bc6579 in call_function () from /lib64/libpython3.7m.so.1.0
#180 0x00007ffff7bfca68 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#181 0x00007ffff7bb3d90 in _PyEval_EvalCodeWithName () from /lib64/libpython3.7m.so.1.0
#182 0x00007ffff7bb4da2 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#183 0x00007ffff7bc63ef in call_function () from /lib64/libpython3.7m.so.1.0
#184 0x00007ffff7c014c2 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#185 0x00007ffff7bb4c02 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#186 0x00007ffff7bc63ef in call_function () from /lib64/libpython3.7m.so.1.0
#187 0x00007ffff7bfcb0c in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#188 0x00007ffff7bb526a in _PyFunction_FastCallDict () from /lib64/libpython3.7m.so.1.0
#189 0x00007ffff7b88e26 in _PyObject_Call_Prepend () from /lib64/libpython3.7m.so.1.0
#190 0x00007ffff7c48939 in slot_tp_call () from /lib64/libpython3.7m.so.1.0
#191 0x00007ffff7bc52cc in _PyObject_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#192 0x00007ffff7bc6579 in call_function () from /lib64/libpython3.7m.so.1.0
#193 0x00007ffff7c014c2 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#194 0x00007ffff7bb3d90 in _PyEval_EvalCodeWithName () from /lib64/libpython3.7m.so.1.0
#195 0x00007ffff7bb543e in _PyFunction_FastCallDict () from /lib64/libpython3.7m.so.1.0
#196 0x00007ffff7b88e26 in _PyObject_Call_Prepend () from /lib64/libpython3.7m.so.1.0
#197 0x00007ffff7c48939 in slot_tp_call () from /lib64/libpython3.7m.so.1.0
#198 0x00007ffff7bc52cc in _PyObject_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#199 0x00007ffff7bc6579 in call_function () from /lib64/libpython3.7m.so.1.0
#200 0x00007ffff7bfca68 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#201 0x00007ffff7bb4c02 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#202 0x00007ffff7bc63ef in call_function () from /lib64/libpython3.7m.so.1.0
#203 0x00007ffff7bfcb0c in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#204 0x00007ffff7bb4c02 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#205 0x00007ffff7bc63ef in call_function () from /lib64/libpython3.7m.so.1.0
#206 0x00007ffff7bfcb0c in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#207 0x00007ffff7bb4c02 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#208 0x00007ffff7bc63ef in call_function () from /lib64/libpython3.7m.so.1.0
#209 0x00007ffff7bfcb0c in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#210 0x00007ffff7bb526a in _PyFunction_FastCallDict () from /lib64/libpython3.7m.so.1.0
#211 0x00007ffff7b88e26 in _PyObject_Call_Prepend () from /lib64/libpython3.7m.so.1.0
#212 0x00007ffff7bc4043 in slot_tp_init () from /lib64/libpython3.7m.so.1.0
#213 0x00007ffff7bc4f27 in _PyObject_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#214 0x00007ffff7bc6579 in call_function () from /lib64/libpython3.7m.so.1.0
#215 0x00007ffff7c014c2 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#216 0x00007ffff7bb4c02 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#217 0x00007ffff7bc63ef in call_function () from /lib64/libpython3.7m.so.1.0
#218 0x00007ffff7bfcb0c in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
--Type <RET> for more, q to quit, c to continue without paging--
#219 0x00007ffff7bb526a in _PyFunction_FastCallDict () from /lib64/libpython3.7m.so.1.0
#220 0x00007ffff7b88e26 in _PyObject_Call_Prepend () from /lib64/libpython3.7m.so.1.0
#221 0x00007ffff7bb597e in PyObject_Call () from /lib64/libpython3.7m.so.1.0
#222 0x00007ffff7bfe214 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#223 0x00007ffff7bb4c02 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#224 0x00007ffff7bc63ef in call_function () from /lib64/libpython3.7m.so.1.0
#225 0x00007ffff7bfcb0c in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#226 0x00007ffff7bb4c02 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#227 0x00007ffff7bc63ef in call_function () from /lib64/libpython3.7m.so.1.0
#228 0x00007ffff7bfcb0c in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#229 0x00007ffff7bb526a in _PyFunction_FastCallDict () from /lib64/libpython3.7m.so.1.0
#230 0x00007ffff7b88e26 in _PyObject_Call_Prepend () from /lib64/libpython3.7m.so.1.0
#231 0x00007ffff7bb597e in PyObject_Call () from /lib64/libpython3.7m.so.1.0
#232 0x00007ffff7c8bfc6 in t_bootstrap () from /lib64/libpython3.7m.so.1.0
#233 0x00007ffff7c0cb84 in pythread_wrapper () from /lib64/libpython3.7m.so.1.0
#234 0x00007ffff7a6c4e2 in start_thread () from /lib64/libpthread.so.0
#235 0x00007ffff7ed1643 in clone () from /lib64/libc.so.6
(gdb) 
```

**Comment by brancomat** [comment]
me and @edigiacomo were looking at this issue... could you provide the source code that triggers the problem?

**Comment by pat1** [comment]
il codice era rmapweb, parte di rmap, ma utilizzato probabilmente in modalità deprecata.
Se ricapita utilizzando le transazione riaprirò il bug.
Per il momento facciamo riferimento a #197
